header is done, adding svg folder with logo
Graviquantum/Barbershop-Borodinski pull request #1
Opened 2021-07-21 14:52 UTC by Graviquantum

2021-07-21 15:04 UTC, bjornsondev commented on index.html
> +                </a>
```suggestion
                <a>
                    <img src="svg/index-logo.svg" width="368" height="120" alt="Логотип барбершопа «Бородинский»">
                </a>
```
вложенность тега, таб

2021-07-21 15:05 UTC, bjornsondev commented on index.html
> +                    <li> <a href="#">Контакты</a> </li>
```suggestion
                    <li> 
                        <a href="#">Информация</a>
                    </li>
```

и так будет с каждым, вложенность, у тебя на лишке будут классы потом, будет не читабельно

2021-07-21 15:06 UTC, bjornsondev commented on index.html
лишняя отбивка

2021-07-21 15:06 UTC, SetanSan commented on index.html
> +                <a>
href?

2021-07-21 15:06 UTC, bjornsondev commented on index.html
> +        <title>Барбершоп «Бородинский»</title>
```suggestion
        <title>Барбершоп «Фурри»</title>
```

2021-07-21 15:09 UTC, SetanSan reviewed
Также нейминг файлов неверный. Желательно бы назвать как-то так: index, catalog, catalog-item

2021-07-21 15:09 UTC, SetanSan commented on index.html
> +                    <li> <a href="#">Информация</a> </li>
Ненужные отступы. Можно перенести тэги <a> на новую строку.

2021-07-21 15:09 UTC, SetanSan commented on index.html
> +                <a>
href?

2021-07-21 15:39 UTC, bjornsondev approved these changes

2021-07-21 16:08 UTC, SetanSan requested changes
You don't need put button tag in a ul and li tags, this is not a list and list item

2021-07-22 13:13 UTC, SetanSan approved these changes
Now you can merge

2021-07-22 13:28 UTC, merged