Adding main with four sections and renaming all html files except index.html
Graviquantum/Barbershop-Borodinski pull request #2
Opened 2021-08-01 15:41 UTC by Graviquantum

2021-08-01 15:54 UTC, SetanSan requested changes

2021-08-01 15:54 UTC, SetanSan commented on index.html
> +                <!--Здесь будет форма вот да, а пока я тупой чтобы ее сделать-->
You can just make an empty Form tag as a mock for now, that's enough

2021-08-01 15:54 UTC, SetanSan commented on index.html
> +                        <img src="img/studio.jpg" width="300" height="223" alt="Интерьер">
"Интерьер" - not enough for lt. Try to write something like "Интерьер барбершопа Бородинский".

2021-08-02 15:22 UTC, SetanSan approved these changes
Nice!

2021-08-02 15:27 UTC, bjornsondev commented on index.html
> +                        <h3>Дорого</h3>
Нет

2021-08-02 15:27 UTC, bjornsondev commented on index.html
> +                <form></form>
че за пустота в теге? если так делайш внутри коммент оставляй хотяб

2021-08-02 18:25 UTC, merged